---
title: "FAQ"
format: html
editor: visual
---

## Is this a Journal?

No. This is an experiment to show one can create a fully operational journal-like platform in a few hours. But there is no reason you can't use it as a journal if you want.

## Did you create a Journal only to host your papers?

Maybe, but this won't be the first [time](https://www.mn.uio.no/cees/english/services/van-valen/evolutionary-theory/volume-1/vol-1-no-1-pages-1-30-l-van-valen-a-new-evolutionary-law.pdf) (story about how Leigh Van Valen created his own Journal [here](https://link.springer.com/article/10.1007/s13752-021-00391-w)).

## Nobody will use this / There is no way this is going to work.

This is not a question, but fine. Most likely I am not going to put the effort on making this page work beyond linking a few of my papers, but building this Anti-Journal allowed me to think freely and explore new ideas without constrains. The learned lessons will for sure be recycled elsewhere. And who knows, maybe you are wrong and people start using it.

## Do you have an Impact Factor?

Impact what?
